# Generated by Django 3.2.4 on 2021-06-15 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AgePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_period', models.IntegerField(choices=[(1, '1 day of life'), (2, '3 - 5 days of life'), (3, '2 months of life'), (4, '4 months of life'), (5, '6 months of life'), (6, '12 months of life'), (7, '18 months of life'), (8, '6 years of life'), (9, '14 years of life'), (10, '16 years of life'), (11, '17+ years of life')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LifePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_period', models.IntegerField(choices=[(1, 'Baby under 18 months'), (2, 'Child from 2 to 16 years'), (3, 'Adult person over 16 years')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vaccines.address')),
                ('age_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='vaccines.ageperiod')),
                ('life_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='vaccines.lifeperiod')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('number_of_dose', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('amount_of_doses', models.IntegerField()),
                ('patients', models.ManyToManyField(blank=True, null=True, related_name='vaccines', through='vaccines.VaccinationDate', to='vaccines.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='vaccinationdate',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine'),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patients', models.ManyToManyField(blank=True, null=True, related_name='queues', to='vaccines.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='ageperiod',
            name='life_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_periods', to='vaccines.lifeperiod'),
        ),
    ]
