# Generated by Django 3.2.4 on 2021-06-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_queue_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationdate',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_dates', to='vaccines.patient'),
        ),
        migrations.AlterField(
            model_name='vaccinationdate',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_dates', to='vaccines.vaccine'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='patients',
            field=models.ManyToManyField(blank=True, null=True, through='vaccines.VaccinationDate', to='vaccines.Patient'),
        ),
    ]
