# Generated by Django 3.2.4 on 2021-06-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_auto_20210616_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='patients',
            field=models.ManyToManyField(blank=True, null=True, related_name='vaccines', through='vaccines.VaccinationDate', to='vaccines.Patient'),
        ),
    ]
